vae:
  latent_dim: 64
  input_shape: [3, 64, 64]
  name: cnn_vae
  ckpt_path: null

## train設定
lr: 1e-4
batch_size: 64
num_epochs: 300
num_workers: 16
input_shape: ${vae.input_shape}

dataset:
  name: "coco"    # "coco" または "cifar10" を指定
  root: "./data/coco"  # coco の画像ディレクトリ
  width: ${vae.input_shape[2]}
  height: ${vae.input_shape[1]}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  
checkpoint:
  base_dir: "./ckpts/VAE/${..dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  topk: 3

logger:
  type: "wandb"    # "tensorboard" または "wandb" を選択

  wandb:
    project: "VAE"
    group: ${...vae.name}_${...dataset.name}
  
  tensorboard:
    log_dir: "./logs/VAE/${now:%Y-%m-%d}/${now:%H-%M-%S}"

hydra:
  run:
    dir: ./outputs/train_vae/${now:%Y-%m-%d}/${now:%H-%M-%S}
