name: SAC-Hug
actor_lr: 1e-4
critic_lr: 1e-4
alpha_lr: 1e-4
gamma: 0.99
tau: 0.005
hidden_dim: 128
policy_noise: 0.2
policy_delay: 2
noise_clip: 0.5
intervention_weight: 1.0
alpha: 0.2
ckpt_path: null